CUSTOMER CHURN RISK (Probability)

Real-World Problem:

A telecom company wants to predict customer churn risk.
Your Objective: Calculate probability and interpret confidence.
Tasks
1.	Simulate churn predictions
2.	Calculate probability of churn
3.	Decide a threshold (e.g., 0.7)
Hint Code
predictions = np.random.rand(20)
high_risk = predictions[predictions > 0.7]
print("High-risk customers:", len(high_risk))
What You Learn
•	Probability outputs
•	Decision thresholds
•	Business impact

In [11]:
# TASK 3: CUSTOMER CHURN RISK (PROBABILITY)
# Real-World Problem:
# A telecom company wants to predict which customers are likely to churn
# using probability outputs from a model.

In [12]:
import numpy as np
import pandas as pd

# Simulate mkodel prediction

In [13]:
# Simulating churn probability predictions for 20 customers
# Each value is between 0 and 1
np.random.seed(42)  # for reproducibility

predictions = np.random.rand(20)
predictions

array([0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864,
       0.15599452, 0.05808361, 0.86617615, 0.60111501, 0.70807258,
       0.02058449, 0.96990985, 0.83244264, 0.21233911, 0.18182497,
       0.18340451, 0.30424224, 0.52475643, 0.43194502, 0.29122914])

DataFrame

In [14]:
# Create customer IDs
customer_ids = [f"CUST_{i+1}" for i in range(20)]

# Create DataFrame
df = pd.DataFrame({
    "Customer_ID": customer_ids,
    "Churn_Probability": predictions
})

df

   Customer_ID  Churn_Probability
0       CUST_1           0.374540
1       CUST_2           0.950714
2       CUST_3           0.731994
3       CUST_4           0.598658
4       CUST_5           0.156019
5       CUST_6           0.155995
6       CUST_7           0.058084
7       CUST_8           0.866176
8       CUST_9           0.601115
9      CUST_10           0.708073
10     CUST_11           0.020584
11     CUST_12           0.969910
12     CUST_13           0.832443
13     CUST_14           0.212339
14     CUST_15           0.181825
15     CUST_16           0.183405
16     CUST_17           0.304242
17     CUST_18           0.524756
18     CUST_19           0.431945
19     CUST_20           0.291229

Define churn risk threshold

In [15]:
# Threshold for high churn risk
threshold = 0.7

Identify High Risk Costumers

In [16]:
# Filter high-risk customers
high_risk_customers = df[df["Churn_Probability"] > threshold]

high_risk_customers

   Customer_ID  Churn_Probability
1       CUST_2           0.950714
2       CUST_3           0.731994
7       CUST_8           0.866176
9      CUST_10           0.708073
11     CUST_12           0.969910
12     CUST_13           0.832443

In [17]:
# Count High Risk cumstomers

print("Total customers:", len(df))
print("High-risk customers:", len(high_risk_customers))

Total customers: 20
High-risk customers: 6

Add Risk Label

In [18]:
# Label customers based on risk
df["Churn_Risk"] = np.where(
    df["Churn_Probability"] > threshold,
    "High Risk",
    "Low Risk"
)

df

   Customer_ID  Churn_Probability Churn_Risk
0       CUST_1           0.374540   Low Risk
1       CUST_2           0.950714  High Risk
2       CUST_3           0.731994  High Risk
3       CUST_4           0.598658   Low Risk
4       CUST_5           0.156019   Low Risk
5       CUST_6           0.155995   Low Risk
6       CUST_7           0.058084   Low Risk
7       CUST_8           0.866176  High Risk
8       CUST_9           0.601115   Low Risk
9      CUST_10           0.708073  High Risk
10     CUST_11           0.020584   Low Risk
11     CUST_12           0.969910  High Risk
12     CUST_13           0.832443  High Risk
13     CUST_14           0.212339   Low Risk
14     CUST_15           0.181825   Low Risk
15     CUST_16           0.183405   Low Risk
16     CUST_17           0.304242   Low Risk
17     CUST_18           0.524756   Low Risk
18     CUST_19           0.431945   Low Risk
19     CUST_20           0.291229   Low Risk

# Busnsiss insight Summary

In [19]:
high_risk_percentage = (len(high_risk_customers) / len(df)) * 100

print(f"{high_risk_percentage:.2f}% of customers are at high risk of churn.")

30.00% of customers are at high risk of churn.